# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users: Gradle settings configured through the IDE *will override* any settings specified in this file.
# For more details on how to configure your build environment visit http://www.gradle.org/docs/current/userguide/build_environment.html
org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=256m -XX:+UseSerialGC -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.configuration-cache=false
org.gradle.workers.max=1
android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true
android.nonFinalResIds=true
android.enableR8.fullMode=false
# fix false positive of PluginLoadedInMultipleProjects:
# (There are Kotlin Gradle Plugins for an android module and a jvm module)
kotlin.pluginLoadedInMultipleProjects.ignore=true